version: "3"

services:
  tor-privoxy:
    restart: always
    image: dockage/tor-privoxy:latest
    ports:
      - "9050:9050" # Tor proxy
      - "9051:9051" # Tor control port
      - "8118:8118" # Privoxy
  books-scraping:
    build:
      dockerfile: Dockerfile
      context: .
    image: googleBooks/scraping:latest
    ports:
      - "8000:3000"
    networks:
      - tor-network

networks:
  tor-network:
    driver: bridge
